const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({channel:'msedge',headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const base = 'http://127.0.0.1:5173';
  const loaded = () => page.getByRole('button',{name:'Refresh project data'}).waitFor({state:'visible'}).then(() => page.waitForFunction(() => !document.querySelector('[aria-label="Refresh project data"]')?.disabled));
  try {
    await page.goto(base); await loaded();
    await page.getByTestId('Pending approvals').click(); await loaded();
    assert.equal(new URL(page.url()).searchParams.get('indicator'),'pending_approvals');
    assert.equal(await page.getByTestId('Pending approvals').getAttribute('aria-pressed'),'true');
    const affected = await (await page.request.get(base + '/api/v1/projects?indicator=pending_approvals&page_size=6')).json();
    await page.getByText(affected.total + ' projects found.',{exact:false}).waitFor();
    const id = affected.items[0].project_id;
    await page.getByRole('row',{name:'Inspect ' + id}).click();
    const quick = page.getByRole('dialog',{name:'Project quick view'});
    await quick.waitFor(); await quick.getByRole('link',{name:'View full details'}).click();
    await page.getByRole('tab',{name:'Overview',exact:true}).waitFor();
    await page.getByRole('tab',{name:'AI Intelligence'}).click();
    await page.getByRole('heading',{name:'Model not yet trained'}).waitFor();
    await page.getByRole('tab',{name:'GIS',exact:true}).click();
    await page.getByText('Placeholder · not a geographic map').waitFor();
    await page.getByRole('tab',{name:'GIS',exact:true}).press('ArrowRight');
    await page.getByRole('heading',{name:'Record history'}).waitFor();
    await page.getByRole('link',{name:'Back to results'}).click(); await loaded();
    assert.equal(new URL(page.url()).searchParams.get('indicator'),'pending_approvals');
    await page.getByRole('button',{name:'Remove Indicator filter'}).click(); await loaded();
    await page.getByRole('button',{name:'Filter projects: Compensation',exact:true}).click(); await loaded();
    assert.equal(new URL(page.url()).searchParams.get('acquisition_stage'),'COMPENSATION');
    await page.getByRole('button',{name:'Quick view P1042',exact:true}).first().click();
    await quick.waitFor(); await page.keyboard.press('Escape');
    assert.equal(await page.getByRole('button',{name:'Quick view P1042',exact:true}).first().evaluate(el => el === document.activeElement),true);
    await page.getByRole('button',{name:'Actions for P1042'}).first().click();
    await page.locator('.row-menu-panel:popover-open').getByRole('button',{name:'Copy project ID'}).click();
    await page.locator('.row-menu-panel:popover-open').getByRole('status').waitFor();
    await page.keyboard.press('Escape');
    await page.getByRole('button',{name:'Clear filters',exact:true}).click(); await loaded();
    const districtBar = page.getByRole('button',{name:'Explore compensation: Pune, Maharashtra',exact:true});
    await districtBar.hover();
    await page.locator('.analytics-tooltip').filter({visible:true}).getByText('with pending approvals',{exact:false}).waitFor();
    await districtBar.click(); await loaded();
    assert.equal(new URL(page.url()).searchParams.get('district'),'Pune');
    assert.equal(new URL(page.url()).searchParams.get('state'),'Maharashtra');
    await page.goto(base + '/projects');
    await page.getByLabel('Search projects').fill('P1042');
    await page.getByRole('button',{name:/^Filters/}).click();
    await page.getByLabel('District filter').fill('Pune');
    await page.getByLabel('Acquisition stage').selectOption('COMPENSATION'); await loaded();
    await page.getByRole('button',{name:'Remove Stage filter'}).click(); await loaded();
    assert.equal(new URL(page.url()).searchParams.get('search'),'P1042');
    assert.equal(new URL(page.url()).searchParams.get('district'),'Pune');
    assert.equal(new URL(page.url()).searchParams.has('acquisition_stage'),false);
    await page.getByRole('button',{name:'Refresh project data'}).click(); await loaded();
    await page.getByText('Last refreshed:',{exact:false}).waitFor();
    await page.keyboard.press('Control+k');
    const palette = page.getByRole('dialog',{name:'Go to anything'});
    await palette.getByRole('combobox').fill('P1042');
    await palette.getByRole('option').first().waitFor();
    await palette.getByRole('combobox').press('ArrowDown');
    await palette.getByRole('combobox').press('Enter');
    await page.getByRole('heading',{name:'Illustrative Eastern Connector'}).waitFor();
    await page.getByLabel('Notification status').click();
    const notices = page.getByRole('dialog',{name:'Review notices'});
    await notices.getByRole('link').first().waitFor();
    await notices.getByRole('button',{name:'Mark shown as read'}).click();
    assert.ok((await page.evaluate(() => JSON.parse(localStorage.getItem('landguard:read-notices')))).length > 0);
    const link = notices.getByRole('link').first();
    const href = await link.getAttribute('href'); await link.click();
    await page.waitForURL('**' + href);
    await page.getByRole('tab',{name:'Overview',exact:true}).waitFor();
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('button',{name:'Toggle navigation'}).click();
    await page.getByRole('dialog',{name:'Navigation drawer'}).getByRole('link',{name:'Projects',exact:true}).click();
    await loaded();
    await page.getByRole('button',{name:/^Filters/}).click();
    const sheet = page.getByRole('dialog',{name:'Project filters'});
    await sheet.getByLabel('District filter').fill('Pune');
    await sheet.getByRole('button',{name:'Show results'}).click(); await loaded();
    await page.locator('.project-cards').getByRole('button',{name:'Quick view P1042'}).click();
    await quick.waitFor();
    const box = await quick.boundingBox();
    assert.ok(Math.abs(box.y + box.height - 844) < 3,'Quick view bottom sheet');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
    await page.screenshot({path:'interaction-mobile-smoke.png',fullPage:true});
    await page.keyboard.press('Escape');
    await page.setViewportSize({width:1440,height:1000});
    await page.goto(base); await loaded();
    await page.screenshot({path:'interaction-dashboard-smoke.png',fullPage:true});
    assert.deepEqual(errors,[]);
    console.log('PASS: all five requested interaction flows, persistent scope, chart tooltips, context menu, keyboard tabs/search, notices/read state, refresh, mobile sheets, and reduced-motion layout.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
