const { chromium } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ reducedMotion: 'reduce', viewport: { width: 1440, height: 1000 } });
  const errors = [];
  const warnings = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'warning') warnings.push(message.text()); });
  const checkWidth = async label => assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, label + ' has document overflow');
  try {
    for (const width of [1440,1280,1024,768,430,390]) {
      await page.setViewportSize({ width, height: 1000 });
      await page.goto('http://127.0.0.1:5173');
      await page.getByRole('heading', { name: 'Compensation vs. possession' }).waitFor();
      await page.getByRole('heading', { name: 'Administrative bottlenecks' }).waitFor();
      await checkWidth('Dashboard ' + width);
      const chartSizes = await page.locator('.recharts-surface').evaluateAll(nodes => nodes.map(n => ({ width: n.getBoundingClientRect().width, height: n.getBoundingClientRect().height })));
      assert.ok(chartSizes.length >= 3 && chartSizes.every(s => s.width > 220 && s.height > 180), 'Chart dimensions ' + width);
      await page.screenshot({ path: 'ui-dashboard-' + width + '-smoke.png', fullPage: true });
      await page.goto('http://127.0.0.1:5173/projects/P1042');
      await page.getByRole('heading', { name: 'Illustrative Eastern Connector' }).waitFor();
      await checkWidth('Details ' + width);
      if ([1440,390].includes(width)) await page.screenshot({ path: 'ui-details-' + width + '-smoke.png', fullPage: true });
      await page.goto('http://127.0.0.1:5173/projects/new');
      await page.getByLabel('Project ID', { exact: true }).waitFor();
      await checkWidth('Form ' + width);
    }
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto('http://127.0.0.1:5173');
    await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).click();
    assert.equal(await page.getByRole('button', { name: 'Expand sidebar' }).getAttribute('aria-expanded'), 'false');
    await page.getByRole('button', { name: 'Expand sidebar' }).click();
    await page.getByLabel('Global project search').fill('P1042');
    await page.getByRole('button', { name: 'Search all projects' }).click();
    await page.getByText('1 matching records', { exact: false }).waitFor();
    assert.ok(page.url().includes('/projects?search=P1042'));
    await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
    await page.getByRole('button', { name: 'Filters', exact: true }).click();
    await page.getByLabel('State filter').fill('Maharashtra');
    await page.getByLabel('District filter').fill('Pune');
    await page.getByText('2 matching records', { exact: false }).waitFor();
    await page.getByLabel('Acquisition stage').selectOption('COMPENSATION');
    await page.getByLabel('Project type', { exact: true }).selectOption('ROAD');
    await page.getByText('1 matching records', { exact: false }).waitFor();
    await page.getByRole('button', { name: 'Remove Stage filter' }).click();
    await page.getByText('2 matching records', { exact: false }).waitFor();
    await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
    await page.getByRole('button', { name: 'Next', exact: true }).click();
    await page.getByText('Page 2 of', { exact: false }).waitFor();
    await page.getByRole('link', { name: 'Analytics', exact: true }).click();
    await page.getByRole('heading', { name: 'Compensation vs. possession' }).waitFor();
    await page.getByLabel('Notification status').click();
    await page.getByRole('dialog', { name: 'Review notices' }).waitFor();
    await page.keyboard.press('Escape');
    await page.getByRole('link', { name: 'GIS Map', exact: true }).click();
    await page.getByRole('heading', { name: 'GIS project view' }).waitFor();
    await page.locator('.leaflet-map').waitFor();
    await page.getByRole('link', { name: 'Projects', exact: true }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Toggle navigation' }).click();
    const dialog = page.getByRole('dialog');
    await dialog.waitFor({ state: 'visible' });
    await page.keyboard.press('Tab');
    assert.equal(await page.evaluate(() => document.querySelector('dialog').contains(document.activeElement)), true);
    await page.keyboard.press('Escape');
    await dialog.waitFor({ state: 'hidden' });
    assert.equal(await page.getByRole('button', { name: 'Toggle navigation' }).evaluate(el => el === document.activeElement), true);
    await page.getByRole('button', { name: 'Toggle navigation' }).click();
    await dialog.getByRole('link', { name: 'Projects', exact: true }).click();
    await page.getByRole('heading', { name: 'All projects' }).waitFor();
    await dialog.waitFor({ state: 'hidden' });
    await page.locator('.project-mobile-card').first().waitFor();
    await checkWidth('Mobile registry');
    await page.screenshot({ path: 'ui-registry-390-smoke.png', fullPage: true });
    await page.goto('http://127.0.0.1:5173/missing-route');
    await page.getByRole('heading', { name: 'This page could not be found.' }).waitFor();
    assert.deepEqual(errors, []);
    assert.deepEqual(warnings, []);
    console.log('PASS: 1440, 1280, 1024, 768, 430, 390 layouts; charts, forms, details, global search, all filters, chips, pagination, navigation, drawer keyboard/focus, GIS map, unknown route; no JavaScript errors or warnings.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
